controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

ackermann_steering_controller:
  ros__parameters:
    use_sim_time: true
    front_steering: true
    rear_wheels_names: [left_rear_wheel_joint, right_rear_wheel_joint]
    # Controller expects right then left for correct inner/outer geometry.
    front_wheels_names: [right_steer_joint, left_steer_joint]
    position_feedback: false
    open_loop: false
    velocity_rolling_window_size: 10
    use_stamped_vel: true
    reference_timeout: 0.5
    wheelbase: 1.90
    front_wheel_track: 1.55
    rear_wheel_track: 1.55
    front_wheels_radius: 0.28
    rear_wheels_radius: 0.40
    odom_frame_id: odom
    base_frame_id: base_footprint
    enable_odom_tf: true
