FROM ros:humble-ros-base-jammy

ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=1000

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        bash-completion \
        can-utils \
        curl \
        git \
        iproute2 \
        nano \
        net-tools \
        python3-colcon-common-extensions \
        python3-pip \
        python3-rosdep \
        python3-vcstool \
        sudo \
        usbutils \
        ros-humble-desktop \
        ros-humble-diagnostic-updater \
        ros-humble-foxglove-bridge \
        ros-humble-geodesy \
        ros-humble-geographic-msgs \
        ros-humble-imu-tools \
        ros-humble-navigation2 \
        ros-humble-nav2-bringup \
        ros-humble-plotjuggler-ros \
        ros-humble-robot-localization \
        ros-humble-rosbag2-storage-mcap \
        ros-humble-tf-transformations \
        ros-humble-tf2-tools \
        ros-humble-xacro \
    && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid "${USER_GID}" "${USERNAME}" \
    && useradd --uid "${USER_UID}" --gid "${USER_GID}" -m -s /bin/bash "${USERNAME}" \
    && echo "${USERNAME} ALL=(root) NOPASSWD:ALL" > "/etc/sudoers.d/${USERNAME}" \
    && chmod 0440 "/etc/sudoers.d/${USERNAME}"

ENV DEBIAN_FRONTEND=dialog
ENV ROS_DISTRO=humble
ENV HEGE_WS=/workspaces/hege_gps_navigation

USER ${USERNAME}
WORKDIR ${HEGE_WS}

CMD ["bash"]
